name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: see the files after checkout
      run: |
        ls -la
    - uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: see the files after cache
      run: |
        ls -la

    - name: install
      run: |
        yarn
    - name: test the app
      env:
        CI: true
      run: |
        yarn test
    - name: build
      run: |
        yarn build
